version: '3'

services:
  app:
    build: .
    image: registry.mpce.mp.br/memorial:latest
    env_file:
      - .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |

        define('WP_HOME', '$WP_HOME');
        define('WP_SITEURL', '$WP_HOME');
        define('FORCE_SSL_ADMIN', true);

    volumes:
      - /var/www/memorial/wp-content/plugins:/var/www/html/wp-content/plugins
      - /var/www/memorial/wp-content/uploads:/var/www/html/wp-content/uploads
      - /var/www/memorial/wp-content/themes:/var/www/html/wp-content/themes

    ports:
      - 12002:80
