version: '3'

services:
  app:
    build: .
    image: registry.mpce.mp.br/memorial:latest
    env_file:
      - .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |

        define('WP_HOME', 'https://memorial-homolog.mpce.mp.br');
        define('WP_SITEURL', 'https://memorial-homolog.mpce.mp.br');
        define('FORCE_SSL_ADMIN', true);

    volumes:
      - /var/www/memorial:/var/www/html
    ports:
      - 12002:80
